### ISSUE TITLE
Creating a dependency cycle with `assertOnAnyBuild` enabled results in an unhelpful error message

### ISSUE THREAD

**Issue by matejdro** [jraska/modules-graph-assert#257]
When creating a dependency cycle between two modules and `assertOnAnyBuild = true`, configuration will fail with unhelpful `StackOverflowError` error message.

```
Failed to notify build listener.
> java.lang.StackOverflowError (no error message)

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

* Exception is:
org.gradle.internal.event.ListenerNotificationException: Failed to notify build listener.
	...
Caused by: java.lang.StackOverflowError
	at com.jraska.module.graph.DependencyGraph.addConnections(DependencyGraph.kt:84)
	at com.jraska.module.graph.DependencyGraph.addConnections(DependencyGraph.kt:84)
	at com.jraska.module.graph.DependencyGraph.addConnections(DependencyGraph.kt:84)
	at com.jraska.module.graph.DependencyGraph.addConnections(DependencyGraph.kt:84)
	at com.jraska.module.graph.DependencyGraph.addConnections(DependencyGraph.kt:84)
	at com.jraska.module.graph.DependencyGraph.addConnections(DependencyGraph.kt:84)
	at com.jraska.module.graph.DependencyGraph.addConnections(DependencyGraph.kt:84)
	at com.jraska.module.graph.DependencyGraph.addConnections(DependencyGraph.kt:84)
	at com.jraska.module.graph.DependencyGraph.addConnections(DependencyGraph.kt:84)
	at com.jraska.module.graph.DependencyGraph.addConnections(DependencyGraph.kt:84)
	at com.jraska.module.graph.DependencyGraph.addConnections(DependencyGraph.kt:84)
	at com.jraska.module.graph.DependencyGraph.addConnections(DependencyGraph.kt:84)
	at com.jraska.module.graph.DependencyGraph.addConnections(DependencyGraph.kt:84)
	at com.jraska.module.graph.DependencyGraph.addConnections(DependencyGraph.kt:84)
	at com.jraska.module.graph.DependencyGraph.addConnections(DependencyGraph.kt:84)
	at com.jraska.module.graph.DependencyGraph.addConnections(DependencyGraph.kt:84)
	at com.jraska.module.graph.DependencyGraph.addConnections(DependencyGraph.kt:84)
	at com.jraska.module.graph.DependencyGraph.addConnections(DependencyGraph.kt:84)
```

Without it enabled, gradle will print helpful error message describing exactly which modules are causing the cycle.

**Comment by jraska** [comment]
Hey, thanks for the explanation. 

I will keep the issue open as it requires implementing cycle detection so it is a possible improvement.
